# Generated by Django 2.2.4 on 2019-08-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='roll_no',
        ),
    ]
